language: cpp
dist: trusty
sudo: required

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - libgmp-dev
      env: COMPILER=gcc VERSION=4.8 CXXFLAGS="-std=c++11" 

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libgmp-dev
      env: COMPILER=gcc VERSION=4.9 JSONCONS_SANITIZE=1 CXXFLAGS="-std=c++11" 

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=gcc VERSION=5  CXXFLAGS="-std=gnu++11" 

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=gcc VERSION=6 JSONCONS_SANITIZE=1

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=gcc VERSION=7 JSONCONS_SANITIZE=1

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: COMPILER=gcc VERSION=8 JSONCONS_SANITIZE=1 CXXFLAGS="-std=c++17 -Werror -Wall -Wextra -Wimplicit-fallthrough -pedantic -Wcast-align -Wcast-qual" 

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: COMPILER=gcc VERSION=8 JSONCONS_SANITIZE=1 CXXFLAGS="-std=c++17 -DJSONCONS_HAS_STRING_VIEW" 

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env: COMPILER=gcc VERSION=9 JSONCONS_SANITIZE=1 CXXFLAGS="-std=c++2a -DJSONCONS_HAS_STRING_VIEW" 

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env: COMPILER=gcc VERSION=8 JSONCONS_SANITIZE=1 CXXFLAGS="-std=gnu++17 -Wall -Wextra -Wimplicit-fallthrough" 

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
            - g++-4.8-aarch64-linux-gnu
            - gcc-4.8-aarch64-linux-gnu
            - g++-4.8-multilib
            - gcc-4.8-multilib
            - qemu
            - qemu-system-arm
      env: COMPILER=clang VERSION=3.9 CROSS_COMPILE=1 ARM_ARCH_DIR=aarch64-linux-gnu GCC_VER=4.8.4 ARM_SETTINGS="armv8-a -target aarch64-linux-gnueabi" CXXFLAGS="-std=c++11" 

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - g++-7
      env: COMPILER=clang VERSION=4.0 CXXFLAGS="-std=c++11" 

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - g++-7
      env: COMPILER=clang VERSION=5.0 CXXFLAGS="-std=gnu++11" 

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - g++-7
      env: COMPILER=clang VERSION=6.0 JSONCONS_SANITIZE=1  CXXFLAGS="-std=c++11 -Wall -Wextra -Wimplicit-fallthrough"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - g++-7
      env: COMPILER=clang VERSION=6.0 CXXFLAGS="-DJSONCONS_NO_DEPRECATED" 

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - g++-7
      env: COMPILER=clang VERSION=7 CXXFLAGS="-DJSONCONS_NO_DEPRECATED" 

    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: CXXFLAGS="-std=c++11"

    - os: osx
      osx_image: xcode8
      compiler: clang
      env: CXXFLAGS="-std=c++11"

    - os: osx
      osx_image: xcode8.1
      compiler: clang
      env: CXXFLAGS="-std=c++11"

    - os: osx
      osx_image: xcode8.2
      compiler: clang
      env: CXXFLAGS="-std=c++11"

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: CXXFLAGS="-std=c++11"

    - os: osx
      osx_image: xcode9
      compiler: clang
      env: CXXFLAGS="-std=c++11"

    - os: osx
      osx_image: xcode9.1
      compiler: clang
      env: CXXFLAGS="-std=c++11"

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: CXXFLAGS="-std=c++11"

    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env: CXXFLAGS="-std=c++11"

    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: CXXFLAGS="-std=c++11"

before_install:
    - |
      # Configure build variables
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        if [[ "$COMPILER" == "gcc" ]]; then
          export CXX=g++-$VERSION CC=gcc-$VERSION;
        fi
        if [[ "$COMPILER" == "clang" ]]; then
          export CXX=clang++-$VERSION CC=clang-$VERSION;
        fi
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        export CXX=clang++ CC=clang;
      fi
install:
    # get CMake (only for systems with brew - macOS)
    - |
     if [[ (-x $(which brew)) ]]; then
       brew update
       brew install cmake 
       brew upgrade cmake
       cmake --version
     fi

    - if [[ "$CROSS_COMPILE" == 1 ]] ; then
        if [[ "$ARM_ARCH_DIR" == "aarch64-linux-gnu" ]] ; then
          mkdir $HOME/linker_bin ;
          ln -s /usr/bin/aarch64-linux-gnu-ld $HOME/linker_bin/ld ;
          echo "SETTING GNU LINKER DIR" ;
          ls -al $HOME/linker_bin/ld ;
          cmake . -DBUILD_TESTS=ON -DCROSS_COMPILE_ARM=ON -DDOWNLOAD_GTEST=ON -DARM_ARCH_DIRECTORY="$ARM_ARCH_DIR" -DARM_GCC_VER="$GCC_VER" -DTARGET_ARCH="$ARM_SETTINGS --prefix=$HOME/linker_bin/"  ${CMAKE_OPTIONS};
        else
          cmake . -DBUILD_TESTS=ON -DCROSS_COMPILE_ARM=ON -DDOWNLOAD_GTEST=ON -DARM_ARCH_DIRECTORY="$ARM_ARCH_DIR" -DARM_GCC_VER="$GCC_VER" -DTARGET_ARCH="$ARM_SETTINGS"  ${CMAKE_OPTIONS};
        fi
      else
        cmake . -DBUILD_TESTS=ON  ${CMAKE_OPTIONS};
      fi
    - make -j2 test_jsoncons
    - cd tests
script:
    - if [[ "$JSONCONS_VALGRIND" == 1 ]]; then
        ctest -T memcheck;
      fi
    - if [[ "$CROSS_COMPILE" == 1 ]]; then
        if [[ "$ARM_ARCH_DIR" == "aarch64-linux-gnu" ]]; then
          qemu-aarch64 -L /usr/aarch64-linux-gnu/ ./test_jsoncons ;
        else
          qemu-arm -L /usr/arm-linux-gnueabi/ ./test_jsoncons ;
        fi
      else
        ./test_jsoncons;
      fi
